set(Plugin-Name "M²aia Registration View")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Jonas Cordes")
set(Plugin-ContactAddress "jtfc@posteo.de")
set(Require-Plugin org.mitk.gui.qt.common org.mitk.gui.qt.elastix.common)
