set(Plugin-Name "M²aia Registration View")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Mannheim University of Applied Sciences")
set(Plugin-ContactAddress "jtfc@posteo.de")
set(Require-Plugin org.mitk.gui.qt.common)
